<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>team.unnamed</groupId>
    <artifactId>commandflow</artifactId>
    <version>0.8.0</version>
    <modules>
        <module>api</module>
        <module>velocity</module>
        <module>bukkit</module>
    </modules>

    <packaging>pom</packaging>

    <distributionManagement>
        <snapshotRepository>
            <id>hibiscus-snapshots</id>
            <url>https://repo.hibiscusmc.com/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>hibiscus-releases</id>
            <url>https://repo.hibiscusmc.com/releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>0.8.0</revision>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>25</source>
                    <target>25</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>